# Generated by Django 2.2.3 on 2019-07-29 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todayemotion',
            old_name='today',
            new_name='to',
        ),
    ]
