# Generated by Django 2.2.3 on 2019-07-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='emotion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.DecimalField(decimal_places=3, default='', max_digits=8),
        ),
        migrations.AddField(
            model_name='post',
            name='lng',
            field=models.DecimalField(decimal_places=3, default='', max_digits=8),
        ),
    ]
