# Generated by Django 2.2.3 on 2019-07-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190718_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lat',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=8),
        ),
        migrations.AlterField(
            model_name='post',
            name='lng',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=8),
        ),
    ]
