# Generated by Django 2.2.3 on 2019-07-22 13:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190722_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lat',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='post',
            name='lng',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=8),
        ),
    ]
