# Generated by Django 2.2.3 on 2019-07-18 10:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190718_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 10, 45, 3, 374103, tzinfo=utc)),
        ),
    ]
