# Generated by Django 2.2.3 on 2019-07-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190718_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='writer',
        ),
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.DecimalField(decimal_places=3, default='', max_digits=8),
        ),
        migrations.AddField(
            model_name='post',
            name='lng',
            field=models.DecimalField(decimal_places=3, default='', max_digits=8),
        ),
        migrations.AlterField(
            model_name='post',
            name='emotion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
