# Generated by Django 2.2.3 on 2019-07-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190718_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lat',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=8),
        ),
        migrations.AlterField(
            model_name='post',
            name='lng',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=8),
        ),
    ]
