# Generated by Django 2.2.3 on 2019-07-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190718_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='post',
            name='lng',
        ),
    ]
